### ISSUE TITLE
Change the API used to fetch news data // 뉴스 데이터를 가져오는 데 사용되는 API 변경 (Naver API -> News API)

### ISSUE THREAD

**Issue by minji0801** [iOS-PPAK/NewsLetter_MinjiKim#2]
# Reason for change // 변경한 이유
The Naver API must send the search query value as a request variable. // 네이버 API는 요청 변수로 검색 쿼리를 반드시 보내야 합니다.
So I need to have a search term to get news data. // 따라서 뉴스 데이터를 얻으려면 검색어가 필요합니다.

<img width="900" alt="Screen Shot 2022-06-08 at 9 36 45 PM" src="https://user-images.githubusercontent.com/49383370/172617936-8657082a-92ff-4df9-b9bc-e07d72843516.png">

# News API
However, the News API can get search or headline news data. // 하지만 News API는 검색 또는 주요 헤드라인 뉴스를 가져올 수 있습니다.

<img width="574" alt="Screen Shot 2022-06-08 at 9 44 09 PM" src="https://user-images.githubusercontent.com/49383370/172619382-ad9144ce-f5b8-4501-8f31-67e66bab1191.png">

- **Search for news articles that mention a specific topic or keyword**
  `GET https://newsapi.org/v2/everything?q=Apple&from=2022-06-08&sortBy=popularity&apiKey=API_KEY`

- **Get the current top headlines for a country or category**
  `GET https://newsapi.org/v2/top-headlines?country=us&apiKey=API_KEY`

## How to get data
<img width="741" alt="Screen Shot 2022-06-08 at 10 59 53 PM" src="https://user-images.githubusercontent.com/49383370/172640069-f4492923-bc2c-4b34-8794-9c3723b259f2.png">

I plan to bring it like this. // 저는 이렇게 가져올 계획입니다.
```swift
struct NewsResponseModel: Decodable {
  var articles: [News]
}

struct News: Decodable {
  let source: Source
  let title: String
  let description: String?
  let url: String?
  let urlToImage: String?
  let publishedAt: String
}

struct Source: Decodable {
  let name: String
}
```

**Comment by WhiteHyun** [comment]
저도 갈아타려구여... 🥹 파이팅
